class APiEndPoint {
static String baseUrl = "https://blaxity.codergize.com/api";
static String imageUrl = "https://blaxity.codergize.com/";
static String clubImage = "https://blaxity.codergize.com";
static String register = "$baseUrl/sign-up";
static String verifyOtp = "$baseUrl/verify-otp";
static String login = "$baseUrl/login";
static String forgotPassword = "$baseUrl/forgot-password";
static String resetPassword = "$baseUrl/reset-password";
// static String changePassword = "$baseUrl/user/change-password";
static String updateProfile = "$baseUrl/user/update-profile";
static String getUserAllData = "https://blaxity.codergize.com/api/users/all";
static String deleteUser = "$baseUrl/user/delete-account/5";
static String reportUser = "$baseUrl/profile/report-user";
static String blockUser = "$baseUrl/profile/report-user";    //////// this the same one with the above url///////////////////////////
static String updateClubDetails = "$baseUrl/club-detail/update/";
static String deleteClubDetails = "$baseUrl/club-detail/delete/";
static String createEvent = "$baseUrl/events";
static String allEvents = "$baseUrl/events";       //////// this the same one with the above url///////////////////////////
static String getEvent = "$baseUrl/events/";   /////eventId should be provided
static String updateEvent = "$baseUrl/events/";   /////eventId should be provided
static String deleteEvent = "$baseUrl/events/{id}";    /////eventId should be provided
static String ownerEvent = "$baseUrl/user/events";
static String createGroup = "$baseUrl/groups";
static String updateGroup = "$baseUrl/groups/";    /////Group Id should be provided
static String DeleteGroup = "$baseUrl/groups/";    /////Group Id should be provided
static String getGroup = "$baseUrl/groups/{groupId}";
static String getAllGroups = "$baseUrl/groups";
static String joinGroup = "$baseUrl/groups/join/";
static String getJoinGroupRequests = "$baseUrl/groups/join-requests/{groupId}";
static String acceptJoinGroupRequests = "$baseUrl/groups/accept-join-request/{groupId}";
static String removeGroupMember = "$baseUrl/groups/{groupId}/members/{memberId}";
static String addGroupAdmin = "$baseUrl/groups/{groupId}/members/{memberId}/promote";
static String sendMessageGroup = "$baseUrl/group-chat/send-message";
static String editMessageGroup = "$baseUrl/group-chat/edit-message/{messageId}";
static String addReactionMessageGroup = "$baseUrl/group-chat/add-reaction";
static String removeReactionMessageGroup = "$baseUrl/group-chat/remove-reaction";
static String deleteMessageGroup = "$baseUrl/group-chat/delete-message/{id}";
static String matchRequest = "$baseUrl/matches/send";
static String getMatches = "$baseUrl/matches";
static String acceptMatchRequest = "$baseUrl/matches/accept";
static String rejectMatchRequest = "$baseUrl/matches/reject";
static String unMatchRequest = "$baseUrl/matches/unmatch";
static String createChat = "$baseUrl/chats";
static String deleteChat = "$baseUrl/chats/{id}";
static String getUserChats = "$baseUrl/chats";
static String getChatMessages = "$baseUrl/chats/messages/{chatId}";
static String sendMessages = "$baseUrl/messages";
static String editMessages = "$baseUrl/messages/{id}";
static String addReaction = "$baseUrl/reactions";
static String updateRemoveReaction = "$baseUrl/update/reactions";
static String deleteReaction = "$baseUrl/messages/{id}";
static String archiveChat = "$baseUrl/chat/archive";
static String unarchiveChat = "$baseUrl/chat/unarchive";
static String getArchiveChats = "$baseUrl/chat/archived/{userId}";
static String createBlogPost = "$baseUrl/blogs";
static String updateBlogPost = "$baseUrl/api/blogs/{id}";
static String deleteBlogPost = "$baseUrl/blogs/{id}";
static String retrieveSingleBlogPost = "$baseUrl/blogs/{id}";
static String updatePost = "$baseUrl/posts/{id}";
static String retrieveAllPost = "$baseUrl/posts";
static String retrieveSinglePost = "$baseUrl/posts/{id}";
static String deletePost = "$baseUrl/posts/{id}";
static String likeUnlikePost = "$baseUrl/posts/like/{id}";
static String addComment = "$baseUrl/posts/comments/{id}";
static String updateComment = "$baseUrl/comments/{id}";
static String deleteComment = "$baseUrl/comments/{id}";
static String addReactionComment = "$baseUrl/comments/reaction/{id}";
static String updateReactionComment = "$baseUrl/reactions/{id}";
static String deleteReactionComments = "$baseUrl/reactions/{id}";
static String addReplyComments = "$baseUrl/comments/reply/{id}";
static String updateReplyComments = "$baseUrl/replies/{id}";
static String deleteReply = "$baseUrl/replies/{id}";
static String reactReply = "$baseUrl/replies/reaction/{id}";
static String deleteReactionReply = "$baseUrl/replies/reactions/{id}";
static String createImages = "$baseUrl/create-images";
}