// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQfJi4kelyyF5MeyyQ43nDrzUKbneQ_Dg',
    appId: '1:1033447313519:android:0964845103bf1a53c4fd9a',
    messagingSenderId: '1033447313519',
    projectId: 'blaxity-8bddb',
    databaseURL: 'https://blaxity-8bddb-default-rtdb.firebaseio.com',
    storageBucket: 'blaxity-8bddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraweYZKeB9D5YIvXGqZF0Ed8TrZBuVII',
    appId: '1:1033447313519:ios:ec172b6b9da6a30ac4fd9a',
    messagingSenderId: '1033447313519',
    projectId: 'blaxity-8bddb',
    databaseURL: 'https://blaxity-8bddb-default-rtdb.firebaseio.com',
    storageBucket: 'blaxity-8bddb.appspot.com',
    iosBundleId: 'codergize.com.blaxity',
  );
}
